namespace :railsnet do
  namespace :db do
    desc "Add default values to the database"
    task :populate => :environment do
      
      puts 'Create network...'
      Network.create(:name => 'RailsNet',
                     :organization => 'TimothyFisher.com',
                     :website => 'http://railsnet.timothyfisher.com',
                     :description => 'This is a sample social network created with RailsNet')
    
      puts 'Populating roles...'
      ['creator', 'administrator', 'user', 'contributor'].each {|r| Role.create(:rolename => r) }

      puts 'Populating countries...'
      [
        ['US', 'United States'],
        ['AD', 'Andorra'],
        ['AE', 'United Arab Emirates'],
        ['AF', 'Afghanistan'],
        ['AG', 'Antigua and Barbuda'],
        ['AI', 'Anguilla'],
        ['AL', 'Albania'],
        ['AM', 'Armenia'],
        ['AN', 'Netherlands Antilles'],
        ['AO', 'Angola'],
        ['AQ', 'Antarctica'],
        ['AR', 'Argentina'],
        ['AS', 'American Samoa'],
        ['AU', 'Austria'],
        ['AS', 'Australia'],
        ['AW', 'Aruba'],
        ['AZ', 'Azerbaijan'],
        ['BA', 'Bosnia and Herzegovina'],
        ['BB', 'Barbados'],
        ['BD', 'Bangladesh'],
        ['BE', 'Belgium'],
        ['BF', 'Burkina Faso'],
        ['BH', 'Bahrain'],
        ['BI', 'Burundi'],
        ['BJ', 'Benin'],
        ['BM', 'Bermuda'],
        ['BO', 'Bolivia'],
        ['BR', 'Brazil'],
        ['BS', 'Bahamas'],
        ['BT', 'Bhutan'],
        ['BU', 'Bouvet Island'],
        ['BV', 'Bulgaria'],
        ['BW', 'Botswana'],
        ['BX', 'Brunei Darussalam'],
        ['BY', 'Belarus'],
        ['BZ', 'Belize'],
        ['CA', 'Canada'],
        ['CC', 'Cocos (Keeling) Islands'],
        ['CF', 'Central African Republic'],
        ['CG', 'Congo'],
        ['CH', 'Switzerland'],
        ['CI', 'Cote D\'Ivoire (Ivory Coast)'],
        ['CK', 'Cook Islands'],
        ['CL', 'Chile'],
        ['CM', 'Cameroon'],
        ['CN', 'China'],
        ['CO', 'Colombia'],
        ['CR', 'Costa Rica'],
        ['CU', 'Cuba'],
        ['CV', 'Cape Verde'],
        ['CX', 'Christmas Island'],
        ['CY', 'Cyprus'],
        ['CZ', 'Czech Republic'],
        ['DE', 'Germany'],
        ['DJ', 'Djibouti'],
        ['DK', 'Denmark'],
        ['DM', 'Dominica'],
        ['DO', 'Dominican Republic'],
        ['DZ', 'Algeria'],
        ['EC', 'Ecuador'],
        ['EE', 'Estonia'],
        ['EG', 'Egypt'],
        ['EH', 'Western Sahara'],
        ['ER', 'Eritrea'],
        ['ES', 'Spain'],
        ['ET', 'Ethiopia'],
        ['FI', 'Finland'],
        ['FJ', 'Fiji'],
        ['FK', 'Falkland Islands (Malvinas)'],
        ['FM', 'Micronesia'],
        ['FO', 'Faroe Islands'],
        ['FR', 'France'],
        ['GA', 'Gabon'],
        ['GB', 'Great Britain (UK)'],
        ['GD', 'Grenada'],
        ['GE', 'Georgia'],
        ['GF', 'French Guiana'],
        ['GH', 'Ghana'],
        ['GI', 'Gibraltar'],
        ['GL', 'Greenland'],
        ['GM', 'Gambia'],
        ['GN', 'Guinea'],
        ['GP', 'Guadeloupe'],
        ['GQ', 'Equatorial Guinea'],
        ['GR', 'Greece'],
        ['GS', 'South Georgia and South Sandwich Islands'],
        ['GT', 'Guatemala'],
        ['GU', 'Guam'],
        ['GW', 'Guinea-Bissau'],
        ['GY', 'Guyana'],
        ['HK', 'Hong Kong'],
        ['HM', 'Heard and McDonald Islands'],
        ['HN', 'Honduras'],
        ['HR', 'Croatia and Hrvatska'],
        ['HT', 'Haiti'],
        ['HU', 'Hungary'],
        ['ID', 'Indonesia'],
        ['IE', 'Ireland'],
        ['IL', 'Israel'],
        ['IN', 'India'],
        ['IO', 'British Indian Ocean Territory'],
        ['IQ', 'Iraq'],
        ['IR', 'Iran'],
        ['IS', 'Iceland'],
        ['IT', 'Italy'],
        ['JM', 'Jamaica'],
        ['JO', 'Jordan'],
        ['JP', 'Japan'],
        ['KE', 'Kenya'],
        ['KG', 'Kyrgyzstan'],
        ['KH', 'Cambodia'],
        ['KI', 'Kiribati'],
        ['KM', 'Comoros'],
        ['KN', 'Saint Kitts and Nevis'],
        ['KP', 'Korea North'],
        ['KR', 'Korea South'],
        ['KW', 'Kuwait'],
        ['KY', 'Cayman Islands'],
        ['KZ', 'Kazakhstan'],
        ['LA', 'Laos'],
        ['LB', 'Lebanon'],
        ['LC', 'Saint Lucia'],
        ['LI', 'Liechtenstein'],
        ['LK', 'Sri Lanka'],
        ['LR', 'Liberia'],
        ['LS', 'Lesotho'],
        ['LT', 'Lithuania'],
        ['LU', 'Luxembourg'],
        ['LV', 'Latvia'],
        ['LY', 'Libya'],
        ['MA', 'Morocco'],
        ['MC', 'Monaco'],
        ['MD', 'Moldova'],
        ['MG', 'Madagascar'],
        ['MH', 'Marshall Islands'],
        ['MK', 'Macedonia'],
        ['ML', 'Mali'],
        ['MM', 'Myanmar'],
        ['MN', 'Mongolia'],
        ['MO', 'Macau'],
        ['MP', 'Northern Mariana Islands'],
        ['MQ', 'Martinique'],
        ['MR', 'Mauritania'],
        ['MS', 'Montserrat'],
        ['MT', 'Malta'],
        ['MU', 'Mauritius'],
        ['MV', 'Maldives'],
        ['MW', 'Malawi'],
        ['MX', 'Mexico'],
        ['MY', 'Malaysia'],
        ['MZ', 'Mozambique'],
        ['NA', 'Namibia'],
        ['NC', 'New Caledonia'],
        ['NE', 'Niger'],
        ['NF', 'Norfolk Island'],
        ['NG', 'Nigeria'],
        ['NI', 'Nicaragua'],
        ['NE', 'Netherlands'],
        ['NO', 'Norway'],
        ['NP', 'Nepal'],
        ['NR', 'Nauru'],
        ['NU', 'Niue'],
        ['NZ', 'New Zealand'],
        ['OM', 'Oman'],
        ['PA', 'Panama'],
        ['PE', 'Peru'],
        ['PF', 'French Polynesia'],
        ['PG', 'Papua New Guinea'],
        ['PH', 'Philippines'],
        ['PK', 'Pakistan'],
        ['PO', 'Poland'],
        ['PM', 'St. Pierre and Miquelon'],
        ['PN', 'Pitcairn'],
        ['PR', 'Puerto Rico'],
        ['PT', 'Portugal'],
        ['PW', 'Palau'],
        ['PY', 'Paraguay'],
        ['QA', 'Qatar'],
        ['RE', 'Reunion'],
        ['RO', 'Romania'],
        ['RU', 'Russian Federation'],
        ['RW', 'Rwanda'],
        ['SA', 'Saudi Arabia'],
        ['SB', 'Solomon Islands'],
        ['SC', 'Seychelles'],
        ['SD', 'Sudan'],
        ['SE', 'Sweden'],
        ['SG', 'Singapore'],
        ['SH', 'St. Helena'],
        ['SI', 'Slovenia'],
        ['SJ', 'Svalbard and Jan Mayen Islands'],
        ['SK', 'Slovak Republic'],
        ['SL', 'Sierra Leone'],
        ['SM', 'San Marino'],
        ['SN', 'Senegal'],
        ['SO', 'Somalia'],
        ['SR', 'Suriname'],
        ['ST', 'Sao Tome and Principe'],
        ['SV', 'El Salvador'],
        ['SY', 'Syria'],
        ['SZ', 'Swaziland'],
        ['TC', 'Turks and Caicos Islands'],
        ['TD', 'Chad'],
        ['TF', 'French Southern Territories'],
        ['TG', 'Togo'],
        ['TH', 'Thailand'],
        ['TI', 'Tajikistan'],
        ['TK', 'Tokelau'],
        ['TM', 'Turkmenistan'],
        ['TN', 'Tunisia'],
        ['TO', 'Tonga'],
        ['TP', 'East Timor'],
        ['TR', 'Turkey'],
        ['TT', 'Trinidad and Tobago'],
        ['TV', 'Tuvalu'],
        ['TW', 'Taiwan'],
        ['TZ', 'Tanzania'],
        ['UA', 'Ukraine'],
        ['UG', 'Uganda'],
        ['UK', 'United Kingdom'],
        ['UM', 'US Minor Outlying Islands'],
        ['UY', 'Uruguay'],
        ['UZ', 'Uzbekistan'],
        ['VA', 'Vatican City State'],
        ['VC', 'Saint Vincent and the Grenadines'],
        ['VE', 'Venezuela'],
        ['VG', 'Virgin Islands (British)'],
        ['VN', 'Viet Nam'],
        ['VU', 'Vanuatu'],
        ['WF', 'Wallis and Futuna Islands'],
        ['WS', 'Samoa'],
        ['YE', 'Yemen'],
        ['YT', 'Mayotte'],
        ['YU', 'Yugoslavia'],
        ['ZA', 'South Africa'],
        ['ZM', 'Zambia'],
        ['ZR', 'Zaire'],
        ['ZW', 'Zimbabwe']
      ].each {|c| Country.create(:abbreviation => c[0], :name => c[1]) }

      puts 'Populating states...'
      us_id = Country.find_by_abbreviation('US').id
      [
        ['ALASKA', 'AK', us_id],
        ['ALABAMA', 'AL', us_id],
        ['ARKANSAS', 'AR', us_id],
        ['AMERICAN SAMOA', 'AS', us_id],
        ['ARIZONA', 'AZ', us_id],
        ['CALIFORNIA', 'CA', us_id],
        ['COLORADO', 'CO', us_id],
        ['CONNECTICUT', 'CT', us_id],
        ['DISTRICT OF COLUMBIA', 'DC', us_id],
        ['WASHINGTON, DC', 'DC', us_id],
        ['DELAWARE', 'DE', us_id],
        ['FLORIDA', 'FL', us_id],
        ['FEDERATED STATES OF MICRONESIA', 'FM', us_id],
        ['GEORGIA', 'GA', us_id],
        ['GUAM', 'GU', us_id],
        ['HAWAII', 'HI', us_id],
        ['IOWA', 'IA', us_id],
        ['IDAHO', 'ID', us_id],
        ['ILLINOIS', 'IL', us_id],
        ['INDIANA', 'IN', us_id],
        ['KANSAS', 'KS', us_id],
        ['KENTUCKY', 'KY', us_id],
        ['LOUISIANA', 'LA', us_id],
        ['MASSACHUSETTS', 'MA', us_id],
        ['MARYLAND', 'MD', us_id],
        ['MAINE', 'ME', us_id],
        ['MARSHALL ISLANDS', 'MH', us_id],
        ['MICHIGAN', 'MI', us_id],
        ['MINNESOTA', 'MN', us_id],
        ['MISSOURI', 'MO', us_id],
        ['NORTHERN MARIANA ISLANDS', 'MP', us_id],
        ['MISSISSIPPI', 'MS', us_id],
        ['MONTANA', 'MT', us_id],
        ['NORTH CAROLINA', 'NC', us_id],
        ['NORTH DAKOTA', 'ND', us_id],
        ['NEBRASKA', 'NE', us_id],
        ['NEW HAMPSHIRE', 'NH', us_id],
        ['NEW JERSEY', 'NJ', us_id],
        ['NEW MEXICO', 'NM', us_id],
        ['NEVADA', 'NV', us_id],
        ['NEW YORK', 'NY', us_id],
        ['OHIO', 'OH', us_id],
        ['OKLAHOMA', 'OK', us_id],
        ['OREGON', 'OR', us_id],
        ['PENNSYLVANIA', 'PA', us_id],
        ['PUERTO RICO', 'PR', us_id],
        ['PALAU', 'PW', us_id],
        ['RHODE ISLAND', 'RI', us_id],
        ['SOUTH CAROLINA', 'SC', us_id],
        ['SOUTH DAKOTA', 'SD', us_id],
        ['TENNESSEE', 'TN', us_id],
        ['TEXAS', 'TX', us_id],
        ['UTAH', 'UT', us_id],
        ['VIRGINIA', 'VA', us_id],
        ['VIRGIN ISLANDS', 'VI', us_id],
        ['VERMONT', 'VT', us_id],
        ['WASHINGTON', 'WA', us_id],
        ['WISCONSIN', 'WI', us_id],
        ['WEST VIRGINIA', 'WV', us_id],
        ['WYOMING', 'WY', us_id]
      ].each {|s| State.create(:name => s[0], :abbreviation => s[1], :country_id => s[2]) }
      
      puts 'Populating widgets...'
      [
        ['Photos', 'Photos', true, 4, 'photos/photos_widget', 'photos', 1, true, false],
        ['Video', 'Video', false, 0, 'videos/videos_widget', 'videos', 1, true, false],
        ['Groups', 'Groups', true, 2, 'groups/groups_widget', 'groups', 1, true, false],
        ['Events', 'Events', true, 3, 'events/events_widget', 'events', 1, true, false],
        ['Members', 'Members', true, 1, 'users/members_home', 'users', 1, true, false],
        ['Forum', 'Forum', true, 6, 'forum_posts/forum_posts_widget', 'forum_posts', 1, true, false],
        ['Html', 'Html', true, 3, 'html_contents/html_content_widget', 'users', 2, false, false],
        ['Blogs', 'Blogs', true, 1, 'blog_posts/blog_posts_widget', 'blog_posts', 2, true, false],
        ['OnlineUsers', 'Online Users', true, 2, 'home/recently_online_widget', 'home', 3, false, true]
       ].each {|w| Widget.create(:name        =>w[0], 
                                 :title       =>w[1],
                                 :active      =>w[2], 
                                 :page_order  =>w[3], 
                                 :path        =>w[4], 
                                 :index_url   =>w[5], 
                                 :col_num     =>w[6],
                                 :menu_item   =>w[7],
                                 :protected   =>w[8])}
                                 
      html_widget = Widget.find_by_name('Html')
      HtmlContent.create(:title => 'Sample HTML Widget',
                         :body => 'This is a <b>sample HTML</b> widget',
                         :widget_id => html_widget.id)     
      
      puts 'Creating users...'
      state_id = State.find_by_name('MICHIGAN').id
      user1 = User.new :first_name=>'Timothy',
                    :last_name=>'Fisher',
                    :sex=>'M',
                    :state_id=>state_id,
                    :country_id=>1,
                    :zip=>'48134',
                    :login=>'admin', 
                    :email=>'admin@email.com',
                    :city=>'Flat Rock',
                    :twitter_id=>'tfisher',
                    :activated_at=>'2009-01-01',
                    :password=>'admin',
                    :password_confirmation=>'admin'
      user1.save
      
     photo = ProfilePhoto.create(:is_profile => true, 
                         :temp_path => File.new(RAILS_ROOT + "/public/images/tim.png"), 
                         :filename => 'tim.png', 
                         :content_type => 'image/png',
                         :user => user1)
      user1.profile_photo = photo
      user1.save
      user1.activate
      user1.roles << Role.find_by_rolename('creator')
      
      user = User.new :first_name=>'John',
                    :last_name=>'Smith',
                    :sex=>'M',
                    :state_id=>state_id,
                    :country_id=>1,
                    :zip=>'48134',
                    :login=>'jsmith', 
                    :email=>'jsmith@email.com',
                    :city=>'Flat Rock',
                    :activated_at=>'2009-01-01',
                    :password=>'jsmith',
                    :password_confirmation=>'jsmith'
      user.save
      user.set_temp_photo()
      user.save
      user.activate
      user.roles << Role.find_by_rolename('user')
      
      puts 'Creating test group...'
      group = Group.new(:name => 'Test Group',
                        :description => 'This is a group for test purposes',
                        :creator_id => user1.id,
                        :featured => false)
     
     photo = ProfilePhoto.create(:is_profile => true, 
                         :temp_path => File.new(RAILS_ROOT + "/public/images/rails.png"), 
                         :filename => 'testgroup.png', 
                         :content_type => 'image/png',
                         :group => group)
                         
     group.profile_photo = photo
     group.save
     
     puts 'Creating an Event...'
     event = Event.new(:name => "Tim's Birthday",
                          :user_id => user1.id,
                          :description => 'The day Tim was born.',
                          :event_type => 'Birthday Party',
                          :start_time => Time.new,
                          :end_time => Time.new,
                          :location => "Tim's House",
                          :street => '25296 Hunter Lane',
                          :city => 'Flat Rock',
                          :website => '',
                          :phone => '555-555-1212',
                          :organized_by => 'Timothy Fisher')
                          
     photo = ProfilePhoto.create(:is_profile => true, 
                         :temp_path => File.new(RAILS_ROOT + "/public/images/testevent.jpg"), 
                         :filename => 'testevent.jpg', 
                         :content_type => 'image/jpg',
                         :event => event)
                         
     event.profile_photo = photo
     event.save
     
      puts 'Creating RSS Feed...'
      RssFeed.create(:name => "Tim's Blog",
                     :url => 'http://feeds.feedburner.com/TimothyFishersBlog',
                     :user => user1)
                     
                     
      puts 'Creating a message...'
      Message.create(:subject=>'Test Message',
                     :body=>'This is just a test message',
                     :sender_id=>user.id,
                     :recipient_id=>user1.id)
         
         
      puts 'Database population done!'
    end
  end
end
