#   Copyright 2009 Timothy Fisher
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

# == Schema Information
# Schema version: 20090206190209
#
# Table name: countries
#
#  id           :integer(4)      not null, primary key
#  name         :string(255)
#  abbreviation :string(255)
#  created_at   :datetime
#  updated_at   :datetime
#

class Country < ActiveRecord::Base
  
  has_many :users
  has_many :states
  
  
  def self.list
    @@country_list
  end

  
    @@country_list = [
      ['US', 'United States'],
      ['AD', 'Andorra'],
      ['AE', 'United Arab Emirates'],
      ['AF', 'Afghanistan'],
      ['AG', 'Antigua and Barbuda'],
      ['AI', 'Anguilla'],
      ['AL', 'Albania'],
      ['AM', 'Armenia'],
      ['AN', 'Netherlands Antilles'],
      ['AO', 'Angola'],
      ['AQ', 'Antarctica'],
      ['AR', 'Argentina'],
      ['AS', 'American Samoa'],
      ['AU', 'Austria'],
      ['AS', 'Australia'],
      ['AW', 'Aruba'],
      ['AZ', 'Azerbaijan'],
      ['BA', 'Bosnia and Herzegovina'],
      ['BB', 'Barbados'],
      ['BD', 'Bangladesh'],
      ['BE', 'Belgium'],
      ['BF', 'Burkina Faso'],
      ['BH', 'Bahrain'],
      ['BI', 'Burundi'],
      ['BJ', 'Benin'],
      ['BM', 'Bermuda'],
      ['BO', 'Bolivia'],
      ['BR', 'Brazil'],
      ['BS', 'Bahamas'],
      ['BT', 'Bhutan'],
      ['BU', 'Bouvet Island'],
      ['BV', 'Bulgaria'],
      ['BW', 'Botswana'],
      ['BX', 'Brunei Darussalam'],
      ['BY', 'Belarus'],
      ['BZ', 'Belize'],
      ['CA', 'Canada'],
      ['CC', 'Cocos (Keeling) Islands'],
      ['CF', 'Central African Republic'],
      ['CG', 'Congo'],
      ['CH', 'Switzerland'],
      ['CI', 'Cote D\'Ivoire (Ivory Coast)'],
      ['CK', 'Cook Islands'],
      ['CL', 'Chile'],
      ['CM', 'Cameroon'],
      ['CN', 'China'],
      ['CO', 'Colombia'],
      ['CR', 'Costa Rica'],
      ['CU', 'Cuba'],
      ['CV', 'Cape Verde'],
      ['CX', 'Christmas Island'],
      ['CY', 'Cyprus'],
      ['CZ', 'Czech Republic'],
      ['DE', 'Germany'],
      ['DJ', 'Djibouti'],
      ['DK', 'Denmark'],
      ['DM', 'Dominica'],
      ['DO', 'Dominican Republic'],
      ['DZ', 'Algeria'],
      ['EC', 'Ecuador'],
      ['EE', 'Estonia'],
      ['EG', 'Egypt'],
      ['EH', 'Western Sahara'],
      ['ER', 'Eritrea'],
      ['ES', 'Spain'],
      ['ET', 'Ethiopia'],
      ['FI', 'Finland'],
      ['FJ', 'Fiji'],
      ['FK', 'Falkland Islands (Malvinas)'],
      ['FM', 'Micronesia'],
      ['FO', 'Faroe Islands'],
      ['FR', 'France'],
      ['GA', 'Gabon'],
      ['GB', 'Great Britain (UK)'],
      ['GD', 'Grenada'],
      ['GE', 'Georgia'],
      ['GF', 'French Guiana'],
      ['GH', 'Ghana'],
      ['GI', 'Gibraltar'],
      ['GL', 'Greenland'],
      ['GM', 'Gambia'],
      ['GN', 'Guinea'],
      ['GP', 'Guadeloupe'],
      ['GQ', 'Equatorial Guinea'],
      ['GR', 'Greece'],
      ['GS', 'South Georgia and South Sandwich Islands'],
      ['GT', 'Guatemala'],
      ['GU', 'Guam'],
      ['GW', 'Guinea-Bissau'],
      ['GY', 'Guyana'],
      ['HK', 'Hong Kong'],
      ['HM', 'Heard and McDonald Islands'],
      ['HN', 'Honduras'],
      ['HR', 'Croatia and Hrvatska'],
      ['HT', 'Haiti'],
      ['HU', 'Hungary'],
      ['ID', 'Indonesia'],
      ['IE', 'Ireland'],
      ['IL', 'Israel'],
      ['IN', 'India'],
      ['IO', 'British Indian Ocean Territory'],
      ['IQ', 'Iraq'],
      ['IR', 'Iran'],
      ['IS', 'Iceland'],
      ['IT', 'Italy'],
      ['JM', 'Jamaica'],
      ['JO', 'Jordan'],
      ['JP', 'Japan'],
      ['KE', 'Kenya'],
      ['KG', 'Kyrgyzstan'],
      ['KH', 'Cambodia'],
      ['KI', 'Kiribati'],
      ['KM', 'Comoros'],
      ['KN', 'Saint Kitts and Nevis'],
      ['KP', 'Korea North'],
      ['KR', 'Korea South'],
      ['KW', 'Kuwait'],
      ['KY', 'Cayman Islands'],
      ['KZ', 'Kazakhstan'],
      ['LA', 'Laos'],
      ['LB', 'Lebanon'],
      ['LC', 'Saint Lucia'],
      ['LI', 'Liechtenstein'],
      ['LK', 'Sri Lanka'],
      ['LR', 'Liberia'],
      ['LS', 'Lesotho'],
      ['LT', 'Lithuania'],
      ['LU', 'Luxembourg'],
      ['LV', 'Latvia'],
      ['LY', 'Libya'],
      ['MA', 'Morocco'],
      ['MC', 'Monaco'],
      ['MD', 'Moldova'],
      ['MG', 'Madagascar'],
      ['MH', 'Marshall Islands'],
      ['MK', 'Macedonia'],
      ['ML', 'Mali'],
      ['MM', 'Myanmar'],
      ['MN', 'Mongolia'],
      ['MO', 'Macau'],
      ['MP', 'Northern Mariana Islands'],
      ['MQ', 'Martinique'],
      ['MR', 'Mauritania'],
      ['MS', 'Montserrat'],
      ['MT', 'Malta'],
      ['MU', 'Mauritius'],
      ['MV', 'Maldives'],
      ['MW', 'Malawi'],
      ['MX', 'Mexico'],
      ['MY', 'Malaysia'],
      ['MZ', 'Mozambique'],
      ['NA', 'Namibia'],
      ['NC', 'New Caledonia'],
      ['NE', 'Niger'],
      ['NF', 'Norfolk Island'],
      ['NG', 'Nigeria'],
      ['NI', 'Nicaragua'],
      ['NE', 'Netherlands'],
      ['NO', 'Norway'],
      ['NP', 'Nepal'],
      ['NR', 'Nauru'],
      ['NU', 'Niue'],
      ['NZ', 'New Zealand'],
      ['OM', 'Oman'],
      ['PA', 'Panama'],
      ['PE', 'Peru'],
      ['PF', 'French Polynesia'],
      ['PG', 'Papua New Guinea'],
      ['PH', 'Philippines'],
      ['PK', 'Pakistan'],
      ['PO', 'Poland'],
      ['PM', 'St. Pierre and Miquelon'],
      ['PN', 'Pitcairn'],
      ['PR', 'Puerto Rico'],
      ['PT', 'Portugal'],
      ['PW', 'Palau'],
      ['PY', 'Paraguay'],
      ['QA', 'Qatar'],
      ['RE', 'Reunion'],
      ['RO', 'Romania'],
      ['RU', 'Russian Federation'],
      ['RW', 'Rwanda'],
      ['SA', 'Saudi Arabia'],
      ['SB', 'Solomon Islands'],
      ['SC', 'Seychelles'],
      ['SD', 'Sudan'],
      ['SE', 'Sweden'],
      ['SG', 'Singapore'],
      ['SH', 'St. Helena'],
      ['SI', 'Slovenia'],
      ['SJ', 'Svalbard and Jan Mayen Islands'],
      ['SK', 'Slovak Republic'],
      ['SL', 'Sierra Leone'],
      ['SM', 'San Marino'],
      ['SN', 'Senegal'],
      ['SO', 'Somalia'],
      ['SR', 'Suriname'],
      ['ST', 'Sao Tome and Principe'],
      ['SV', 'El Salvador'],
      ['SY', 'Syria'],
      ['SZ', 'Swaziland'],
      ['TC', 'Turks and Caicos Islands'],
      ['TD', 'Chad'],
      ['TF', 'French Southern Territories'],
      ['TG', 'Togo'],
      ['TH', 'Thailand'],
      ['TI', 'Tajikistan'],
      ['TK', 'Tokelau'],
      ['TM', 'Turkmenistan'],
      ['TN', 'Tunisia'],
      ['TO', 'Tonga'],
      ['TP', 'East Timor'],
      ['TR', 'Turkey'],
      ['TT', 'Trinidad and Tobago'],
      ['TV', 'Tuvalu'],
      ['TW', 'Taiwan'],
      ['TZ', 'Tanzania'],
      ['UA', 'Ukraine'],
      ['UG', 'Uganda'],
      ['UK', 'United Kingdom'],
      ['UM', 'US Minor Outlying Islands'],
      ['UY', 'Uruguay'],
      ['UZ', 'Uzbekistan'],
      ['VA', 'Vatican City State'],
      ['VC', 'Saint Vincent and the Grenadines'],
      ['VE', 'Venezuela'],
      ['VG', 'Virgin Islands (British)'],
      ['VN', 'Viet Nam'],
      ['VU', 'Vanuatu'],
      ['WF', 'Wallis and Futuna Islands'],
      ['WS', 'Samoa'],
      ['YE', 'Yemen'],
      ['YT', 'Mayotte'],
      ['YU', 'Yugoslavia'],
      ['ZA', 'South Africa'],
      ['ZM', 'Zambia'],
      ['ZR', 'Zaire'],
      ['ZW', 'Zimbabwe']
    ] 

  
end
